# .env
spring.config.import=optional:file:./.env[.properties]
spring.application.name=lets-play

# MongoDB
spring.mongodb.uri=${MONGODB_URI}


# JWT
application.security.jwt.secret-key=${APPLICATION_SECURITY_JWT_SECRET_KEY}
application.security.jwt.expiration=${APPLICATION_SECURITY_JWT_EXPIRATION}


# Multipart
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB

server.port=9090

server.ssl.enabled=true
server.ssl.key-store=classpath:lets-play.p12
server.ssl.key-store-password=${KEYSTORE_PASSWORD}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=lets-play